#include "lab3.h"

/* createCenteredArray
	This function takes in the size(size must be odd, or else function will return NULL) of an array, and allocates
	memory for an array based on that size. The array will be centered, meaning the returned pointer is at the 
	center of the array, such that half of the indices are negative and the other half is positive. Function 
	returns pointer to center element of array or NULL if the array could not be created.		
*/
int * createCenteredArray(int size)
{
	int * array;
	
	if(size % 2 != 0)	//check if given size is odd
	{
		//Allocate memory for size provided. Store result into int pointer.
		array = malloc(size *sizeof(int));
		if(NULL == array)	//check if malloc had failed. If so, returns NULL;
		{
			return NULL;
		}		
	}
	else //return NULL on the condition that size is even
	{
		return NULL;
	}
	
	return array+ (size/2);		//Return int pointer offset to array's center.
}

/* getAtIndex
	This function takes in an int array pointer, the size of the array, and an index to be found within the array.
	Returns the value of array at the given index if the index is valid for the array, or  1 on error. 	
*/
int getAtIndex(int * array, int size, int index)
{
	int number = 1;	//Value to determine whether index was found. 1 = not found. 0= found.
	
	//Traverse through array, starting at the least negative index until the end of the array.
	for(int x =(-1*(size/2)); x < size;x++) // (-1*(size/2) --> multipies the quotient of size and 2 by -1.
	{				        //   - This is to insure the loop starts at the "begining" of array. 
		if(x == index)		//Test if given index matches any of the array's indices.
		{
			number = array[x];	//Number value is set to value of array at given index
		}
	} 

	return number;  
}

/* averageUpperHalf
	This function takes an int array pointer and the size of the array. It returns the average of the upper half of 
	the array(Essientially, the non negative indices).
*/
float averageUpperHalf(int *array, int size)
{
	int sum =0;
	float average =0;
	
	//Iterate through loop, starting at the zeroth element, ending at the last element.
	for(int x =0; x<size -(size/2);x++) // (size -(size/2)) --> Subtracts the quotient from size in order to
	{					//- get the size of the upper half.

		sum += array[x];
	}

	average = (float)sum / (size-(size/2)); //Calculate the average by diving the sum by the size of the upper half.

	return average;
}

/* freeCenteredArray
	This function takes in an array pointer generated by creatCenteredArray, the size of that array, and simply
	frees the space allocated to that array. 
*/

void freeCenteredArray(int *array, int size)
{
	if(size %2 != 0) //Test if given size was odd or even
	{
		free(array-(size/2));	//Free int pointer offset to the begining of the array(what was origianlly allocated)
	}
	else
	{
		//Tell user that function can not operate properly with the given size
		printf("Warning: Could not free array becuase size was even. Please enter an odd size.\n");
	}
}



